# Generated by Django 6.0.3 on 2026-03-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='static/sagar')),
                ('info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Traded', 'Traded')], default='Available', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gallery',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_received', to='postbook.post')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
